# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [2]:
import numpy as np

In [2]:
#Ejercicio 1
import numpy as np
# 1. Definimos el arreglo
a = np.array([1, 2, 3, 4])
resultado = np.all(a != 0)

print(f"¿Es verdad que ninguno de los elementos es cero?: {resultado}")# ejercicio 1

¿Es verdad que ninguno de los elementos es cero?: True


In [3]:
#Ejercicio 2
hay_ceros = np.any(a == 0)

resultado_alterno = not hay_ceros
print(f"Resultado con lógica inversa: {resultado_alterno}")

Resultado con lógica inversa: True


In [4]:
#Ejercicio 3

a = np.array([1, 2, np.nan, np.inf])

contiene_nan = np.isnan(a).any()

contiene_inf = np.isinf(a).any()

print(f"¿Contiene valores NaN?: {contiene_nan}")
print(f"¿Contiene valores infinitos?: {contiene_inf}")

print(f"Máscara de NaNs: {np.isnan(a)}")
print(f"Máscara de Infs: {np.isinf(a)}")


¿Contiene valores NaN?: True
¿Contiene valores infinitos?: True
Máscara de NaNs: [False False  True False]
Máscara de Infs: [False False False  True]


In [5]:
#ejercicio 4
a = np.array([1, 2, np.inf])

resultado = np.isinf(a).any()

print(f"¿El arreglo contiene algún valor infinito?: {resultado}")

posicion = np.where(np.isinf(a))
print(f"El infinito se encuentra en el índice: {posicion[0]}")


¿El arreglo contiene algún valor infinito?: True
El infinito se encuentra en el índice: [2]


In [6]:
#Ejercicio 5
a = np.array([1, np.nan, 3])
resultado = np.isnan(a).any()

print(f"¿El arreglo contiene valores NaN?: {resultado}")
cuantos_nan = np.isnan(a).sum()
print(f"Cantidad de valores faltantes (NaN): {cuantos_nan}")


¿El arreglo contiene valores NaN?: True
Cantidad de valores faltantes (NaN): 1


In [8]:
#Ejercicio 6
# 1. Definimos los arreglos
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])

mayor = a > b
mayor_o_igual = a >= b
menor = a < b
menor_o_igual = a <= b

print(f"¿a > b?  : {mayor}")         
print(f"¿a >= b? : {mayor_o_igual}") 
print(f"¿a < b?  : {menor}")         
print(f"¿a <= b? : {menor_o_igual}") 

¿a > b?  : [False False  True]
¿a >= b? : [False  True  True]
¿a < b?  : [ True False False]
¿a <= b? : [ True  True False]


In [10]:
#Ejercicio 7
a = np.array([1, 7, 13, 105])
memoria_total = a.nbytes
print(f"Arreglo: {a}")
print(f"Tipo de dato: {a.dtype}")
print(f"Cantidad de elementos: {a.size}")
print(f"Memoria total ocupada: {memoria_total} bytes")

Arreglo: [  1   7  13 105]
Tipo de dato: int64
Cantidad de elementos: 4
Memoria total ocupada: 32 bytes


In [13]:
#Ejercicio 8
ceros = np.zeros(10)
unos = np.ones(10)
cincos = np.ones(10) * 5

print(f"Ceros:  {ceros}")
print(f"Unos:   {unos}")
print(f"Cincos: {cincos}")

Ceros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Unos:   [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Cincos: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [14]:
#Ejercicio 9
arreglo = np.arange(30, 71)
print(arreglo)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [15]:
#Ejercicio 10
numeros_pares = np.arange(30, 71, 2)

print(numeros_pares)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [17]:
#Ejercicio 11
matriz_identidad = np.eye(3)
print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#Ejercicio 12
rng = np.random.default_rng()
numero = rng.random()

print(numero)

0.1251906152264851


In [21]:
#Ejercicio 13
rng = np.random.default_rng()
arreglo_normal = rng.standard_normal(15)
print(arreglo_normal)

[ 0.54629096  0.36009354  0.35834777 -0.34671144 -0.97443538 -0.59969357
 -0.29003633  0.52452259  0.24347622  1.28329121  1.86937909  0.90088222
  1.56659917 -0.30732966 -0.0762268 ]


In [22]:
#Ejercicio 14

arreglo = np.arange(15, 56)

print(arreglo[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [23]:
#Ejercicio 15

vector = np.linspace(5, 50, 10)

print(vector)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [24]:
#Ejercicio 16
vector = np.arange(21)
vector[9:16] *= -1
print(vector)


[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [25]:
#Ejercicio 17

a = np.array([1, 2, 3])
lista_python = a.tolist()
print(f"Resultado: {lista_python}")
print(f"Tipo de objeto: {type(lista_python)}")


Resultado: [1, 2, 3]
Tipo de objeto: <class 'list'>


In [26]:
#Ejercicio 18
l = [1, 2, 3]

arreglo = np.array(l)
print(f"Arreglo: {arreglo}")
print(f"Tipo de objeto: {type(arreglo)}")

Arreglo: [1 2 3]
Tipo de objeto: <class 'numpy.ndarray'>


In [27]:
#Ejercicio 19

m = np.array([[1, 2], [3, 4]])
m_booleanos = (m % 2 == 0)

m_solo_pares = m[m % 2 == 0]

print("Matriz original:")
print(m)
print("\nMatriz de verificación (Booleanos):")
print(m_booleanos)
print("\nValores que cumplieron la condición:")
print(m_solo_pares)


Matriz original:
[[1 2]
 [3 4]]

Matriz de verificación (Booleanos):
[[False  True]
 [False  True]]

Valores que cumplieron la condición:
[2 4]


In [28]:
#Ejercicio 20
m = np.array([[1, 2, 3], [4, 5, 6]])

filas, columnas = m.shape

print(f"La matriz tiene {filas} filas y {columnas} columnas.")
print(f"Forma total (shape): {m.shape}")


La matriz tiene 2 filas y 3 columnas.
Forma total (shape): (2, 3)
